### ISSUE TITLE
Allow using external postgresql database

### ISSUE THREAD

**Issue by mildred** [altLab/liquid-feedback-docker#1]
An external postgresql database would allow managing the data separately, have it running in a volume outside docker, have backups ... You should consider allowing docker linking to a postgresql database.

**Comment by pangelo** [comment]
This is definitely something we would like to have.

The current all-in-one version of the Dockerfile is just meant to help simplify building LF for testing/evaluation purposes.

I'll keep this issue open as a reminder of this.

Thanks.

**Comment by pangelo** [comment]
This is currently being tracked in #9
